version: "3"


services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: on-failure

  alembic:
    build:
      context: .
    command: sh -c "alembic upgrade head"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: on-failure

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      - REDIS_HOST=0.0.0.0
    ports:
      - "6379:6379"
    volumes:
      - .:/app
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    depends_on:
      - postgres
      - alembic
    restart: always

  bot:
    build:
      context: .
    command: sh -c "python main.py"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: on-failure