"""add banned

Revision ID: 0346fe3967d8
Revises: 296ca666b3ae
Create Date: 2024-06-29 12:47:07.866608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0346fe3967d8'
down_revision: Union[str, None] = '296ca666b3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.Boolean(), server_default=sa.false()))

    op.alter_column('users', 'banned', server_default=None, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###
